## Numpy

We dont use python functions slow, thats why numpy comes to picture where all the numpy functions are written in C language, hence the functions execute fast

Numpy will convert our DataFrames into numbers to find patterns inside it

Features

1. It is fast
2. Behind the scenes optimizations written in C
3. Vectorization via broadcasting (avoiding loops)

In [1]:
import numpy as np

## DataTypes and Attributes

Numpy's main datatype is is ndrray (nd-array -> N dimensional Array)

In [9]:
# 1D array (1, 3) 
# 1 row, 3 column
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [10]:
# 2D array (2, 3)
# 2 row 3 column
a2 = np.array([[1, 2, 3.6],
             [4, 5, 6.2]])
a2

array([[1. , 2. , 3.6],
       [4. , 5. , 6.2]])

In [11]:
# 3D array (2, 3, 3)
# 2 tables 3 rows 3 columns
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
a1.shape

(3,)

In [13]:
a2.shape

(2, 3)

In [14]:
a3.shape

(2, 3, 3)

In [15]:
# No of Dimensions
(a1.ndim, a2.ndim, a3.ndim)

(1, 2, 3)

In [16]:
# Datatype
(a1.dtype, a2.dtype, a3.dtype)

(dtype('int64'), dtype('float64'), dtype('int64'))

In [17]:
# size -> gives the numbe rof elements present in the array
(a1.size, a2.size, a3.size)

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [23]:
# Pandas is built on top of numpy
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.6
1  4.0  5.0  6.2


## Creating Arrays

In [28]:
## array of 1's, specify the size of array
ones = np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# array of 0's 
zero_array = np.zeros((4,3))
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
## Genrating array of numbers with steps(jumps)
number_array = np.arange(3, 36, 2)
number_array

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35])

In [31]:
# Creating a random array
# np.random.randint(stating-no, ending-no, size-of-array)
random_array = np.random.randint(0, 10, size=(3,5))
random_array

array([[8, 9, 9, 2, 3],
       [6, 1, 2, 7, 3],
       [2, 2, 7, 8, 7]], dtype=int32)

In [35]:
(random_array.shape, random_array.size)

((3, 5), 15)

In [34]:
# Another way of creating random array in range of values 0 to 1
np.random.random((5,3))

array([[0.40562157, 0.45789986, 0.61559761],
       [0.40516238, 0.25001987, 0.16792165],
       [0.17378379, 0.74475024, 0.34195694],
       [0.89219458, 0.90966577, 0.75820591],
       [0.72805018, 0.64167968, 0.01031118]])

In [36]:
np.random.rand(4,5)

array([[0.57391354, 0.2030191 , 0.88955593, 0.73419242, 0.76219165],
       [0.28854795, 0.13091288, 0.9521224 , 0.34266123, 0.23282724],
       [0.56867874, 0.99049241, 0.10966974, 0.90250196, 0.92840231],
       [0.89924716, 0.27825358, 0.16609338, 0.26840154, 0.42701623]])


This random numbers aren't random, they are generated through seed also called as Psuedo seed

In [40]:
#if we put seed value then random array wont get changed after re-runing multiple times
np.random.seed(seed=5657)
random_a1 = np.random.randint(10, size=(5,3))
random_a1

array([[3, 4, 3],
       [5, 6, 6],
       [5, 9, 1],
       [3, 9, 6],
       [2, 8, 1]], dtype=int32)

In [44]:
np.random.seed(7) #random seed is set to 7
random_a2 = np.random.random((5,4))
random_a2

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518],
       [0.97798951, 0.53849587, 0.50112046, 0.07205113],
       [0.26843898, 0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 , 0.90959353],
       [0.21338535, 0.45212396, 0.93120602, 0.02489923]])


## Viewing arrays and matrixes

In [47]:
## Finding unique elements
np.unique(random_array)

array([1, 2, 3, 6, 7, 8, 9], dtype=int32)

In [48]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
a2[0]

array([1. , 2. , 3.6])

In [51]:
#using slicing
# viewing first 2 elements of all arrays
a3[ :2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [53]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[8, 4, 9, 0, 2],
         [0, 7, 6, 2, 9],
         [9, 5, 1, 0, 0],
         [9, 1, 1, 5, 3]],

        [[2, 0, 4, 8, 7],
         [1, 4, 9, 3, 6],
         [7, 1, 0, 2, 7],
         [0, 0, 9, 8, 2]],

        [[0, 5, 5, 0, 9],
         [0, 8, 4, 5, 1],
         [4, 0, 7, 2, 0],
         [3, 9, 8, 3, 7]]],


       [[[1, 0, 1, 4, 6],
         [1, 0, 1, 0, 1],
         [8, 4, 1, 6, 8],
         [5, 2, 4, 7, 4]],

        [[1, 2, 8, 5, 2],
         [9, 6, 2, 5, 7],
         [7, 5, 5, 6, 0],
         [6, 4, 6, 2, 6]],

        [[8, 7, 0, 5, 8],
         [9, 7, 7, 6, 2],
         [5, 6, 1, 9, 3],
         [4, 0, 3, 5, 6]]]], dtype=int32)

In [54]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [57]:
#Get first 3 numbers of inner most arrays
a4[:, :, :, :3]

array([[[[8, 4, 9],
         [0, 7, 6],
         [9, 5, 1],
         [9, 1, 1]],

        [[2, 0, 4],
         [1, 4, 9],
         [7, 1, 0],
         [0, 0, 9]],

        [[0, 5, 5],
         [0, 8, 4],
         [4, 0, 7],
         [3, 9, 8]]],


       [[[1, 0, 1],
         [1, 0, 1],
         [8, 4, 1],
         [5, 2, 4]],

        [[1, 2, 8],
         [9, 6, 2],
         [7, 5, 5],
         [6, 4, 6]],

        [[8, 7, 0],
         [9, 7, 7],
         [5, 6, 1],
         [4, 0, 3]]]], dtype=int32)